### ISSUE TITLE
'The collection type 'Newtonsoft.Json.Linq.JObject' is not supported' exception thrown when loading entities

### ISSUE THREAD

**Issue by ayaalmax** [CynosuraPlatform/Cynosura.Studio#48]
### How to fix:
- Add a package reference to Microsoft.AspNetCore.Mvc.NewtonsoftJson
- Update Startup.ConfigureServices to call AddNewtonsoftJson: services.AddMvc().AddNewtonsoftJson();

**Comment by bacr** [comment]
Fixed in 30b62e02dc7356926f83d75846321862746c8415
